### PR TITLE
Fixed grammar and spelling errors on the readme.md, huge code cleanup on the entire project.

### PR DESCRIPTION
**Pull request by Tarkan-Zarrouk**
I fixed the grammar and spelling errors on your readme.md. 
Huge code cleanup. Not 1 line of code on your client is actually custom besides readme.md.

😐

### CODE REVIEW

**Comment by Tarkan-Zarrouk** [comment]
+6,220 −6,665  added and deleted. Stop making this shit client lmao

**Comment by Tarkan-Zarrouk** [comment]
Here's a tip.  look at your errors and fix them.

**Review by Tarkan-Zarrouk — COMMENTED** [review]
its the best shit ive seen

**Comment by master7720** [comment]
wdym "you guys" its only 1 dev and its the 3000iq dude

**Comment by 3000IQPlay** [comment]
> wdym "you guys" its only 1 dev and its the 3000iq dude

true

**Pull request merged**
